### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by luizeduardotj** [luizeduardotj/language-school#1]
### [Mock](https://dribbble.com/shots/13979977-Language-School/attachments/5593794?mode=media)

![sidebar](https://user-images.githubusercontent.com/46824002/89717055-7256d500-d991-11ea-85cc-b86c8f429b2b.png)

**Comment by enzodanjour** [comment]
Eu pego essa.

**Comment by luizeduardotj** [comment]
Done in #7
