### ISSUE TITLE
TopBar

### ISSUE THREAD

**Issue by luizeduardotj** [luizeduardotj/language-school#2]
### [Mock](https://dribbble.com/shots/13979977-Language-School/attachments/5593794?mode=media)

![top-bar](https://user-images.githubusercontent.com/46824002/89717063-87336880-d991-11ea-8a72-f55aa3738593.png)

**Comment by enzodanjour** [comment]
Eu faço.

**Comment by luizeduardotj** [comment]
Finished #9
