### ISSUE TITLE
Friends Schedule

### ISSUE THREAD

**Issue by luizeduardotj** [luizeduardotj/language-school#5]
### [Mock](https://dribbble.com/shots/13979977-Language-School/attachments/5593794?mode=media)

![friends-schedule](https://user-images.githubusercontent.com/46824002/89717090-d4afd580-d991-11ea-99e0-f6af6d7a3add.png)

**Comment by MarcusXavierr** [comment]
Deixa que eu tento fazer esse

**Comment by luizeduardotj** [comment]
Finish #8
